Initial Life calendar interface and Canvas RRA
ryanmercado/StuHQ pull request #10
Opened 2024-02-02 00:45 UTC by cdewitt02

My initial life calendar work, idk if it still works with the new JSON strategy

2024-02-02 00:55 UTC, ATRJR submitted a review, later dismissed
Looks good! Approved.

2024-02-03 00:17 UTC, Grayson34 commented on backend/calendar/user_events.py
need to add more error checks in here. validate id's, event_id's and any other possible edge cases

2024-02-03 00:19 UTC, Grayson34 commented on backend/calendar/user_events.py
cant use absolute path to communicate with db, it wont work on our computers

2024-02-03 00:19 UTC, Grayson34 commented on backend/calendar/to_do_list.py
absolute reference for db

2024-02-03 00:20 UTC, Grayson34 commented on backend/calendar/user_events.py
needs function to fetch a persons events

2024-02-03 00:22 UTC, Grayson34 commented on backend/calendar/to_do_list.py
some of these functions (like get_todo_list) isnt gonna be needed when we are just storing it all in db (it wll need to be written in the other file)

2024-02-05 21:45 UTC, ryanmercado commented on backend/calendar/canvasAPI/driver.py
we probably don't need this

2024-02-05 21:51 UTC, ryanmercado commented on backend/calendar/to_do_list.py
> +            WHERE usr_id = ? AND start_epoch >= ? AND start_epoch <= ? AND is_important = 1
is_important -> on_to_do_list

2024-02-05 22:03 UTC, ryanmercado requested changes

2024-02-05 22:03 UTC, ryanmercado commented on backend/calendar/user_events.py
> +def update_event(event_id, new_event_title):
Change to update all required fields

2024-02-05 22:11 UTC, ryanmercado approved these changes
Looks good, Lets get grayson on still

2024-02-06 17:49 UTC, Grayson34 commented on backend/calendar/to_do_list.py
> +    def get_todo_list(self, usr_id):
is this needed

2024-02-06 17:50 UTC, Grayson34 commented on backend/calendar/to_do_list.py
> +        user_events.create_event(usr_id, 1, created_epoch, event_desc, event_type, event_title, start_epoch, end_epoch, on_to_do_list)
event_id set to 1?

2024-02-06 18:25 UTC, Grayson34 approved these changes
barring the two tickets this can be approve

2024-02-06 18:25 UTC, merged