added check in addRecipe to ensure recipe does not already exist
ryanmercado/StuHQ pull request #13
Opened 2024-02-05 20:53 UTC by Grayson34

removed unnecessary files

2024-02-05 22:15 UTC, ryanmercado approved these changes
Looks good, we should make tests if we haven't yet though

2024-02-05 22:22 UTC, cdewitt02 requested changes
minor id name change

2024-02-05 22:22 UTC, cdewitt02 commented on backend/recipe/Recipe.py
>              cursor.execute('UPDATE recipes SET recipe_lists = ? WHERE id = ?', (updated_recipes_json, id))
I believe that id is now usr_id in the updated DB, all tables now have "usr_id" rather that "id"

2024-02-06 18:46 UTC, ryanmercado commented on backend/recipe/Recipe.py
> +#     name='Luke',
rip gerber

2024-02-06 18:51 UTC, WilliamSterner approved these changes
good

2024-02-06 18:53 UTC, cdewitt02 approved these changes
Nice!

2024-02-06 18:53 UTC, merged