added routing for calendar backend functions
ryanmercado/StuHQ pull request #23
Opened 2024-02-12 21:34 UTC by WilliamSterner

added routes for calendar backend

2024-02-12 21:43 UTC, cdewitt02 requested changes

2024-02-12 21:43 UTC, cdewitt02 commented on backend/main.py
I think we are going to just have one all encompassing FLASK app for all phases of the project, 'stuAPI' instead of 'calendarAPI'. Same changes for 'recipeAPI'.

2024-02-12 21:43 UTC, cdewitt02 commented on backend/main.py
William Sterner, could you do me a favor and change line 47 of to_do_list to say user_events.usr_id_exists(usr_id), may mistake

2024-02-12 21:43 UTC, cdewitt02 commented on backend/main.py
misspelled delete_event on line 161

2024-02-14 19:55 UTC, cdewitt02 approved these changes
Looks good now

2024-02-15 20:25 UTC, ryanmercado approved these changes

2024-02-15 20:29 UTC, ryanmercado commented
Make sure imports still work, I messed with them to resolve merge conflict

2024-02-15 20:50 UTC, merged