resume doc basic interface
ryanmercado/StuHQ pull request #24
Opened 2024-02-13 20:33 UTC by ATRJR

added basic interface for resume doc, cannot be accessed unless you add link or whatever in index but im goted

2024-02-13 20:59 UTC, ryanmercado requested changes
Also wth do you mean by it needs a link? 

As far as the resume questionnaire goes, we should probably make a questionnaire component for each of our 8 sections, starting with the mandatory ones, and then display them to the user one at a time, not allowing submit to be pressed unless required fields are filled.

Section order should probably be:

1. General Information
2. Skills List
3. Job Experience (1 job mandatory, optionally add more)
4. Project experience (1 mandatory...)
5. Extracurricular Activities List (each one will have a couple pieces ofdata)
6. Life Objective (fully optional)
7. Relevant Coursework List (fully optional)
8. Volunteer Work (fully optional)
9. Awards List (fully optional)


Will also probably need an interface for choosing to fill out optional fields

Will also need an interface for viewing each questionnaire portion again and editing it.

2024-02-13 20:59 UTC, ryanmercado commented on student-hub-app/src/Resume/restumeDoc.js
> +  }
This questionnaire ordering makes very little sense. In theory, it should first be General info, then skills, then job experience (with the ability to add multiple jobs) info, then projects (same deal) then extracurricular, and for each of these you will need to talk with Owen or reference the DB to see what fields are mandatory and what values each field needs

2024-02-14 19:52 UTC, cdewitt02 requested changes

2024-02-14 19:52 UTC, cdewitt02 commented on student-hub-app/src/Calendar/calendarLand.js
this doesn't do anything why are u committing it it will lead to merge conflicts

2024-02-16 16:26 UTC, closed without merging

2024-02-16 16:26 UTC, Grayson34 commented
this pr should be taken down until way more work is done